### ISSUE TITLE
Gretty broken for Jetty >= 9.4.15

### ISSUE THREAD

**Issue by GFriedrich** [gretty-gradle-plugin/gretty#120]
Hi @javabrett,
seems that Gretty currently breaks for all Jetty versions >= 9.4.15.
The internal Jetty API has been changed and the Gretty Runner fails to find a method:
```
groovy.lang.MissingMethodException: No signature of method: org.eclipse.jetty.util.resource.ResourceCollection.findResource() is applicable for argument types: (java.lang.String) values: [META-INF/jetty9.4-env.xml]
Possible solutions: getResource(java.lang.String), newResource(java.lang.String), newResource(java.io.File), newResource(java.net.URI), newResource(java.net.URL), newResource(java.nio.file.Path)
	at org.akhikhl.gretty.JettyConfigurerImpl.findResourceURL(JettyConfigurerImpl.groovy:246) ~[gretty-runner-jetty94-2.3.1.jar:na]
```
This method has been dropped via https://github.com/eclipse/jetty.project/commit/8969c9a18cd86e0eff3dd5651fe6ddb165b2ad58#diff-ca8a7c586007366cbd605eeecbd70d1b
Would be awesome if you could fix it.
Thanks in advance!

**Comment by gregorko** [comment]
We are having the same problem. A fix would be nice.
