### ISSUE TITLE
Option to remove EXECUTING prompt?

### ISSUE THREAD

**Issue by ksrb** [gretty-gradle-plugin/gretty#124]
Is there a simple way to remove the auto-updating prompt when running a task like `appRun`?

![image](https://user-images.githubusercontent.com/3750409/58651117-4f2c9200-82c5-11e9-9764-d375b931b92d.png)

# Additional details
If it's not something easy then no worries and close the issue 😞.

It's causing issues within the Cygwin mintty terminal while using tmux:
![image](https://user-images.githubusercontent.com/3750409/58651261-a7fc2a80-82c5-11e9-8aef-d167381aa3e1.png)

**Comment by FriedrichFroebel** [comment]
This rather seems to be a Gradle-specific problem in combination with your setup. You may try `./gradlew appRun --console=plain` as per [docs](https://docs.gradle.org/current/userguide/command_line_interface.html#sec:command_line_customizing_log_format) instead.

**Comment by ksrb** [comment]
Thanks, rather new to gradle so I had a feeling that something like `--console=plain` existed just didn't know how to google for it!
