### ISSUE TITLE
Warnings appear with Gradle 6.0.1 - baseName, version, destinationDir

### ISSUE THREAD

**Issue by 7ep** [gretty-gradle-plugin/gretty#137]
I get the following warnings with this plugin:
```
The baseName property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the archiveBaseName property instead.
The version property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the archiveVersion property instead.
The destinationDir property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the destinationDirectory property instead.
```
When I remove the gretty plugin, these warnings go away.  That's why I am certain it's coming from Gretty.

If you wish you may reproduce this locally - just use my app, https://github.com/7ep/demo.git , the only dependency is jdk8 or above.

Simply run `gradlew coveros --warning-mode all` to observe the warnings on the first several lines of output

**Comment by boris-petrov** [comment]
Thank you for the heads up. [This is fixed in master](https://github.com/gretty-gradle-plugin/gretty/commit/b94a0d8befa4f262496046576e550462c318d24a). It will be released at some point.
