### ISSUE TITLE
"Use random ports" may bind to already used ports

### ISSUE THREAD

**Issue by f4lco** [gretty-gradle-plugin/gretty#138]
We use Gretty mainly for integration tests. We observed a test flakiness stemming from Gretty, which tried to bind already used ports when configuring the "use random ports" feature.

The analysis is as follows:
1. Gretty chooses ports (for Tomcat/Jetty, status port, service port) upfront. It picks a random free port by binding to 0, and unbinds it immediately again.
2. At a later stage, the previously identified port gets passed to server configurer, or the respective server sockets for internal communication ("service protocol"). 

In between choosing a free port and binding it there exists a sufficient amount of time for another process to chip in and bind the same port, causing the second step to fail for one of the processes.

I think a fix consists of the following two steps:
* Ensuring that ports are not chosen upfront, but rather by the individual server connectors - they have to bind with '0', and then the actually bound port has to be retrieved via the `localPort` property.
* The service protocol must be reworked, such that the ports of the two server sockets are bound as long as possible (ideally over the entire execution of Gretty from deployment to tear-down if applicable).

I have a patch ready and I am currently testing it. Are you interested in a PR?

**Comment by javabrett** [comment]
Thanks @f4lco yes a PR would be welcome.
