### ISSUE TITLE
IntelliJ unable to attach to debugging process with Gradle 5.6

### ISSUE THREAD

**Issue by drodriguezalfayate** [gretty-gradle-plugin/gretty#152]
When using `gradle 5.6` if you start `gretty` with `appRunDebug` or `farmRunDebug`, IntelliJ is not able to attach to debug process. This issue is described in: https://youtrack.jetbrains.com/issue/IDEA-226922

Problem seems to be located in `DefaultLauncher.groovy`, javaExec method is setting manually debug options as:

```
jvmArgs.add '-Xdebug'
String debugArg = "-Xrunjdwp:transport=dt_socket,server=y,suspend=${params.debugSuspend ? 'y' : 'n'},address=${params.debugPort}"
jvmArgs.add debugArg
```

This debug configuration is JDK 5 compatible, although it works perfectly in IntelliJ with newer JDKS (tested with OpenJDK 11).

In Gradle 5.6, JavaExec introduces debugging support, and - I think - that gretty debug and JavaExec debug options are being mixed, so IntelliJ is unable to locate the process.

In order to avoid this problem, following changes should be made to `DefaultLauncher.groovy`, detecting if Gradle 5.6 API is active, and enabling new debug options, or in other case, going back to default implementation:

```
        // Checking if we are in pre 5.6 Gradle API
        if(spec.metaClass.getMetaProperty('debugOptions')==null) {
          if(log.isDebugEnabled()) {
            log.debug("Before Gradle 5.6 setting DebugOptions manually")
          }
          jvmArgs.add '-Xdebug'
          String debugArg = "-Xrunjdwp:transport=dt_socket,server=y,suspend=${params.debugSuspend ? 'y' : 'n'},address=${params.debugPort}"
          jvmArgs.add debugArg
        } else {
          if(log.isDebugEnabled()) {
            log.debug("Gradle 5.6 or upper, using DebugOptions on javaExec")
          }
          spec.debug = true
          spec.debugOptions {jd ->
            jd.enabled = true
            jd.port = params.debugPort
            jd.server = true
            jd.suspend = params.debugSuspend
          }
        }
```

I have attached a pull request to resolve this issue https://github.com/gretty-gradle-plugin/gretty/pull/151

**Comment by boris-petrov** [comment]
This has been fixed, thanks to @drodriguezalfayate!

@drodriguezalfayate - do you think https://github.com/gretty-gradle-plugin/gretty/issues/157 is the same issue as this one here?

**Comment by drodriguezalfayate** [comment]
I don't think it's exactly the same, following the issue he is referencing  (https://github.com/akhikhl/gretty/issues/435), he is asking about the possibility to launch and debug the process of gretty in one click from IntelliJ. Without using provided `*debug` task facilities, but making the `appRunWar` implementing `JavaForkOptions`...

**Comment by boris-petrov** [comment]
I see, OK, thanks. We'll leave it open then, so someone like you can come and fix it. :smile:

**Comment by dulakm** [comment]
Just confirming that it seems to me as different issue as well. 

Btw. implementing it would be awesome (but no pressure 😄).
