### ISSUE TITLE
Check deployment options

### ISSUE THREAD

**Issue by f4lco** [gretty-gradle-plugin/gretty#165]
After deciding #161, we quite possibly need new deployment options for at least two branches (see also discussion in #144)
- "legacy" pre-Jakarta Gretty in maintenance mode (bugfixes for everything prior to Jetty 10 and Tomcat 10)
- post-Jakarta JDK 8 build, possibly with a subset of servlet containers (Tomcat 10)
- post-Jakarta JDK 11 build, with all servlet containers

Travis build/test pipelines and deployment stages should be updated accordingly.

**Comment by boris-petrov** [comment]
I believe this issue is resolved - we've decided on supporting Gretty 3.x for non-Jakarta containers and Gretty 4.x with all Jakarta containers and requiring JDK11+.
