### ISSUE TITLE
The app is started twice

### ISSUE THREAD

**Issue by mvysny** [gretty-gradle-plugin/gretty#169]
Good day, I have an app at https://github.com/mvysny/karibu10-helloworld-application . When you run `./gradlew appRun`, the app compiles and starts and Gretty prints "Press any key to stop the server.". However, after that, Gretty stops the app and starts it again.

Steps to reproduce:

1. git clone https://github.com/mvysny/karibu10-helloworld-application
2. cd karibu10-helloworld-application
3. ./gradlew clean appRun --info

You can see basically the log output duplicated two times; for example the text "Vaadin application has started in DEBUG MODE".

When I add ServletContextListener, I can see that the contextDestroyed() is called, then the app is initialized again.

**Comment by mvysny** [comment]
Apologies: I realized that it could be Vaadin or Vaadin Gradle plugin modifying files somewhere in the `build/` folder, so I've added:

```kotlin
    onScanFilesChanged = listOf<groovy.lang.Closure<Any?>>(closureOf<List<String>> {
        println("!!!!!")
        println(this)
    })
```
to the build script, and indeed it printed out:

```
    !!!!!
[/home/mavi/work/my/vok/karibu10-helloworld-application/build/resources/main/META-INF/VAADIN, /home/mavi/work/my/vok/karibu10-helloworld-application/build/resources/main/META-INF/VAADIN/build]
```

So now I need to figure out who is responsible for writing those files.
```

**Comment by mvysny** [comment]
Found the case: someone (most probably VaadinServlet) creates an empty folder `/home/mavi/work/my/vok/karibu10-helloworld-application/build/resources/main/META-INF/VAADIN/build`, which then Gretty detects as a changed file and forces hot-redeployment:

```
changed file /home/mavi/work/my/vok/karibu10-helloworld-application/build/resources/main/META-INF/VAADIN affects project :
file /home/mavi/work/my/vok/karibu10-helloworld-application/build/resources/main/META-INF/VAADIN is in output of :, servlet-container will be restarted
changed file /home/mavi/work/my/vok/karibu10-helloworld-application/build/resources/main/META-INF/VAADIN/build affects project :
file /home/mavi/work/my/vok/karibu10-helloworld-application/build/resources/main/META-INF/VAADIN/build is in output of :, servlet-container will be restarted
15:31:40 WARN  Ignoring deprecated socket close linger time
```

Would it be possible for Gretty to not hot-redeploy an app if only an empty folder is created with no contents, since that doesn't affect the classpath?

**Comment by cyraid** [comment]
Is this still an issue?

**Comment by mvysny** [comment]
@cyraid I'm sorry for accidental reopening. The issue was on Vaadin's side, creating a folder unnecessarily, which caused Gretty to hot-redeploy. I am closing this issue as WON'T FIX.
