### ISSUE TITLE
Please publish the plugin to Maven Central

### ISSUE THREAD

**Issue by mvysny** [gretty-gradle-plugin/gretty#192]
Since Bintray+JCenter is being terminated, it would be great to publish Gretty to Maven Central. Also, certain Gretty artifacts are only present on jcenter() and will stop working once jcenter is dead.

Please find the announcement here: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Publishing to Maven Central is annoying as hell, but I can give you a helping hand if need be (I've done the migration just now myself).

**Comment by boris-petrov** [comment]
@mvysny - thanks for the heads up! We will definitely have to migrate to Maven Central, yes. I was just thinking about pinging @javabrett in the last few days about that very thing. If you have the time to explain briefly what the process is and where you had troubles it would probably help us! Thanks a lot!

**Comment by mvysny** [comment]
Hi, sure thing! The initial set of steps is painful to get through, but afterwards the release process is not that bad.

I've summarized my knowledge here: https://mvysny.github.io/jcenter-is-dead/ - it links a couple of articles which explains the entire process in a sane way, and most importantly link to up-to-date example projects (using Gradle 6.8.1).

**Comment by boris-petrov** [comment]
So actually publishing directly to the [Gradle Plugin Portal](https://plugins.gradle.org/) is probably the best option. What do you think, @mvysny, @f4lco, @javabrett?

**Comment by mvysny** [comment]
Ah right, great catch! Gradle hosts the plugins in a separate repo at https://plugins.gradle.org/m2/ . I agree - that's probably the best place to put the plugin.

**Comment by f4lco** [comment]
Yes, Gradle Plugin Portal seems to be the best option! Thanks @mvysny for bringing up the issue with JCenter.

**Comment by wolfs** [comment]
Yes.

**Comment by big-guy** [comment]
@wolfs is right. I think the options are...

1. Combine the non-plugin projects into a plugin jar (e.g., through shading/fatjar)
2. Move non-plugin project code into plugin projects (like above, but at the source level)
3. Publish non-plugin projects to Maven Central and publish plugin projects to publish plugin

The last one is similar to what Spring does and what I would do. The non-plugin projects are published to a regular repository and the plugin project is published to the plugin portal.

**Comment by wolfs** [comment]
If my understanding is correct, the Gretty project currently publishes
- non-plugin and plugin projects to Bintray 
- plugin projects to the plugin portal

So the plugin artifact is on Bintray and on the plugin portal.

**Comment by f4lco** [comment]
Please also take note while the Gretty build should be free of references to JCenter, the plugin scripts are not:

https://github.com/gretty-gradle-plugin/gretty/blob/0af9f24156755cd692a308c2d37e7c6cacb6ac6c/pluginScripts/gretty-SNAPSHOT.plugin#L12-L15

Remember
* to update the most recent plugin scripts with the new repository defintion
* decide if antique plugin scripts of older releases also get an update with a new repository definition
* and update the [documentation](https://gretty-gradle-plugin.github.io/gretty-doc/Getting-started.html) which also mentions jcenter to date

These are necessary steps to transition to Maven Central.

**Comment by steffenyount** [comment]
Hi, I saw the v3.0.4 artifacts are getting published to `https://plugins.gradle.org/m2/org/gretty/gretty/3.0.4/` and so I tried using them...

Can you make it so that the plugin dependencies are located via the
     `buildscript.repositories`
repo search path instead of the 
     `project.repositories`
repo search path

Ideally all my plugins and their dependencies could be resolved with repo settings like the following in my settings.gradle file:

```
pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}
```

But my build with these settings fails to find `org.gretty:gretty-runner-jetty94:3.0.4` since it is looking for for that dependency in maven central (in the project.repositories) instead of the gradle plugin portal (in the buildscript.repositories)...

**Comment by boris-petrov** [comment]
@steffenyount - unfortunately, [as far as I understand](https://github.com/gretty-gradle-plugin/gretty/issues/192#issuecomment-795200696), we can publish only plugin JARs in the Gradle Plugin Portal. This means that the other parts of Gretty have to go somewhere. Until now, this has been JCenter. This will change soon and they will go to Maven Central. So, I think, you'll still need `mavenCentral` in your `pluginManagement` block but at least you won't need `jcenter`. :)

**Comment by boris-petrov** [comment]
Snapshots and releases now go to Maven Central. Hooray!
