### ISSUE TITLE
Publish snapshots to Maven Central instead of Bintray

### ISSUE THREAD

**Issue by boris-petrov** [gretty-gradle-plugin/gretty#212]
As Bintray goes read-only from tomorrow, March 31st. Perhaps we can do that to Maven Central after that?

**Comment by edeak** [comment]
any updates on this?

**Comment by boris-petrov** [comment]
Not yet. @javabrett is trying to get publishing to Maven Central to work.

**Comment by boris-petrov** [comment]
Snapshots and releases now go to Maven Central. Hooray!
