### ISSUE TITLE
Gretty-runner-jetty94:3.0.4 is missing?

### ISSUE THREAD

**Issue by Stianhn** [gretty-gradle-plugin/gretty#227]
Hi guys/gals

I'm trying to upgrade gretty to version 3.0.4 but I'm running into this issue:
`Execution failed for task ':appRun'.
> Could not resolve all files for configuration ':grettyRunnerJetty94'.
   > Could not find org.gretty:gretty-runner-jetty94:3.0.4.`

When Im looking into the maven repos I can only find 3.0.3. Am I suppose to use this version? If so, how do I configure this?

I also tried to look for runners for jetty 10/11 without finding anything. 

Any help is much appreciated.

**Comment by boris-petrov** [comment]
@Stianhn - do you have [jcenter](https://mvnrepository.com/artifact/org.gretty/gretty-runner-jetty94/3.0.4) in your repos? As Gretty is still currently published there.

**Comment by Stianhn** [comment]
Ah, thanks for pointing that out @boris-petrov .
