### ISSUE TITLE
Set custom classpath for servlet engine

### ISSUE THREAD

**Issue by acabrerizosanchez** [gretty-gradle-plugin/gretty#237]
Hello, 

The issue that I'm trying to address is how to avoid different library versions loaded on the servlet container classpath. 

When I start tomcat using gretty I can see that the classpath already contains groovy-json-X.Y.Z.jar and groovy-X.Y.Z.jar. For example if using this simple build.gradle file with java 11, gretty 4.0.0 and gradle 6.9.1, associated to a dummy project only containing a Helloworld.html,  the running tomcat shows a classpath containing groovy-2.5.12.jar and groovy-json-2.5.12.jar. I assume that it is included by gretty as the dummy project does not rely on groovy at all.

I wonder if I could use any gretty configuration to avoid the inclusion of those groovy-json-X.Y.Z.jar and groovy-X.Y.Z.jar libraries within the servlet engine classpath. Otherwise any other web application using a different version of groovy-json and groovy will also include them into the classpath leading to the issue of having loaded the same library with different versions.

```groovy
plugins {
    id 'java'
    id 'war'
    id 'org.gretty' version '4.0.0'
}



group 'com.webapp.sample'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8


repositories {
    jcenter()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

gretty{
    httpPort = 8081
    servletContainer = 'tomcat10'
}
```

**Comment by f4lco** [comment]
Hello @acabrerizosanchez, unfortunately, I have trouble reproducing your issue.

> the running tomcat shows a classpath containing groovy-2.5.12.jar and groovy-json-2.5.12.jar

How would you exactly do that? I tried using Gretty's own diagnostics, the `showClasspath` task:

```
$ gradle showClasspath

> Task :showClassPath
Runner classpath:
 file:/Users/falco/.gradle/caches/modules-2/files-2.1/org.gretty/gretty-runner-tomcat10/4.0.0/56e07dd5d2033b6c8047fab0cfd545e848cabcd0/gretty-runner-tomcat10-4.0.0.jar
 file:/Users/falco/.gradle/caches/modules-2/files-2.1/org.gretty/gretty-runner-tomcat/4.0.0/8c3ed5ea4e6391f805a37f6d4d103dc605e2398a/gretty-runner-tomcat-4.0.0.jar
 file:/Users/falco/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-jasper/10.0.10/8b5c905b8493020c01adfbf3b541a9acf7e597d/tomcat-embed-jasper-10.0.10.jar
 file:/Users/falco/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-websocket/10.0.10/5fc778b19b8706e173e22ad218a6df4011ac54c3/tomcat-embed-websocket-10.0.10.jar
 ... (truncated)
/gretty-repro classpath:
 file:/Users/falco/tmp/gretty-repro/build/classes/java/main
 file:/Users/falco/tmp/gretty-repro/build/resources/main
```

While the _runner_ process has many classpath entries (the process that starts Tomcat), the _webapp classpath_ only contains two entries: the classes and resources directory of the dummy webapp. The webapp classpath does not seem to include Groovy at all.
I wouldn't rule out right away that a bug in Gretty exists, but please check again if you can find any evidence for Gretty to put Groovy JARs on the webapp classpath. 
I also bring up one known limitation: if you use Gretty's filter functionality, we may add `groovy-jmx` and `groovy-servlet` on the webapp classpath with a different Groovy version. If you were willing to address that, I could point out relevant files in the Gretty source.

**Comment by acabrerizosanchez** [comment]
Hello, 
I've created a minimum project at https://github.com/acabrerizosanchez/gretty4DependencyEvaluation  and following the next steps I can reproduce it:

1. Clone the repo
2. Then execute **./gradlew** showClasspath (next is my output that includes groovy dependencies :( )

```
$ ./gradlew showClasspath

> Task :showClassPath
Runner classpath:
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.gretty/gretty-runner-tomcat10/4.0.0/56e07dd5d2033b6c8047fab0cfd545e848cabcd0/gretty-runner-tomcat10-4.0.0.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.gretty/gretty-runner-tomcat/4.0.0/8c3ed5ea4e6391f805a37f6d4d103dc605e2398a/gretty-runner-tomcat-4.0.0.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-jasper/10.0.10/8b5c905b8493020c01adfbf3b541a9acf7e597d/tomcat-embed-jasper-10.0.10.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-websocket/10.0.10/5fc778b19b8706e173e22ad218a6df4011ac54c3/tomcat-embed-websocket-10.0.10.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-core/10.0.10/75e766eac367fbb61a24fc7da27d8f7a846ae42b/tomcat-embed-core-10.0.10.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-el/10.0.10/65744da3b27f9f57e053aa354faf8207f8f563f/tomcat-embed-el-10.0.10.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/jakarta.servlet/jakarta.servlet-api/5.0.0/2e6b8ccde55522c879434ddec3714683ccae6867/jakarta.servlet-api-5.0.0.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.gretty/gretty-runner/4.0.0/c5f2ba4b5d13ed6085a47490339a8d030458abd7/gretty-runner-4.0.0.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.slf4j/log4j-over-slf4j/1.7.32/152d3b5e2470bb8e898bd82886fc783361e2c32b/log4j-over-slf4j-1.7.32.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.apache.tomcat/tomcat-annotations-api/10.0.10/d57b6526ec742dc4f085fb833e4ff0753d8b6e5/tomcat-annotations-api-10.0.10.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.eclipse.jdt/ecj/3.18.0/4d5d0911b30db24c8eb844702c8adf8e434314ff/ecj-3.18.0.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/commons-cli/commons-cli/1.3.1/1303efbc4b181e5a58bf2e967dc156a3132b97c0/commons-cli-1.3.1.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/commons-io/commons-io/2.4/b1b6ea3b7e4aa4f492509a4952029cd8e48019ad/commons-io-2.4.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.1.3/d90276fff414f06cb375f2057f6778cd63c6082f/logback-classic-1.1.3.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.gretty/gretty-common/4.0.0/859e92177136cb944a782fad4a17ed044858fb32/gretty-common-4.0.0.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.32/cdcff33940d9f2de763bc41ea05a0be5941176c3/slf4j-api-1.7.32.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-core/1.1.3/e3c02049f2dbbc764681b40094ecf0dcbc99b157/logback-core-1.1.3.jar
 file:/Users/acabrerizo/.gradle/wrapper/dists/gradle-6.9.1-all/dm0s7mte56boux4w1pzdul20n/gradle-6.9.1/lib/groovy-all-1.3-2.5.12.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-cli-commons/2.5.12/101d6c7b0c3c93431c452eaacfc8063cfd81cb3e/groovy-cli-commons-2.5.12.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-json/2.5.12/1cb5dc7473fd4c872bf5e2f054d21e0cfd47ffea/groovy-json-2.5.12.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/2.5.12/c5a65ece40ef0030e6958af990bd6d83b4e206ec/groovy-2.5.12.jar
 file:/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/commons-cli/commons-cli/1.4/c51c00206bb913cd8612b24abd9fa98ae89719b1/commons-cli-1.4.jar
/Helloworld classpath:
 file:/private/tmp/gretty4DependencyEvaluation/build/classes/java/main
 file:/private/tmp/gretty4DependencyEvaluation/build/resources/main

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 596ms
1 actionable task: 1 executed
```

**Comment by f4lco** [comment]
Hello @acabrerizosanchez the output is still looking good to me, working as intended, I see that there are no Groovy JARs on the classpath of the webapp. 

Debugging further, I added a small example servlet to your reproducer and inspected the servlet in the debugger, just to make sure we have not regressed from Gretty 3.x:

![image](https://user-images.githubusercontent.com/29141485/133992746-c7debd21-48f2-47c2-81cd-ec12944e4773.png)

The debugger shows that the classloader of the servlet just searches two directories listed under '/Helloworld classpath:' from the previous diagnostic output, none of them are related to Groovy.
Also, I tried to load `groovy.lang.GroovySystem`using that classloader, and got a `ClassNotFoundException` back.
In turn, I assume that indeed the webapp cannot see any Groovy-related class.
I'm a bit out of luck on reproducing your issue. What would make you think Groovy is on the webapp classpath of the reproducer? Are there any other symptoms or errors?

**Comment by acabrerizosanchez** [comment]
Hello, 

Now I see your point when you say: "I see that there are no Groovy JARs on the classpath of the **webapp**."

Anyway I've just created another project on github (https://github.com/acabrerizosanchez/gretty2DependencyEvaluation) that is equivalent to the previous one but relies on gretty 2.3 and java 8 (because actually these are the versions we are using and because it is simpler to get the classpath). I've also added an auxiliary class for extracting the classpath and make the jsp to show the full list of jars loaded.

In order to reproduce it please follow the next steps:

- git clone
- Start tomcat ./gradlew tomcatRun
- And then access http://localhost:8585/Helloworld/hello.jsp  . There you can see all the _jars_ currently loaded including groovy-2.4.15. Next is the full list:

```
/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.gretty/gretty-runner-tomcat8/2.3.1/bbfdf679d85ea017dc92e8223ad40c1588219f7d/gretty-runner-tomcat8-2.3.1.jar
/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.gretty/gretty-runner-tomcat8plus/2.3.1/d08dc70a1a30615480990bccdfa211b3adbfc08e/gretty-runner-tomcat8plus-2.3.1.jar
/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.gretty/gretty-runner-tomcat/2.3.1/d971b58524fda18540554c60dcbc461ece87cd3b/gretty-runner-tomcat-2.3.1.jar
/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-jasper/8.0.53/849e2cd5c1a3795330bd5258041499be5ddb9a7a/tomcat-embed-jasper-8.0.53.jar
/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-websocket/8.0.53/778d9a96de1adc79850992e316f626061836c2a5/tomcat-embed-websocket-8.0.53.jar
/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-core/8.0.53/9bfd668c63434597ac1d561c9434c166d93fff21/tomcat-embed-core-8.0.53.jar
/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-el/8.0.53/a0804253d7fbe387305b312c32b30c41b85f408/tomcat-embed-el-8.0.53.jar
/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/javax.servlet/javax.servlet-api/3.1.0/3cd63d075497751784b2fa84be59432f4905bf7c/javax.servlet-api-3.1.0.jar
/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.gretty/gretty-runner/2.3.1/32dbf74e7f24076dacce8e6819da4ba9b1c8b0e9/gretty-runner-2.3.1.jar
/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.slf4j/log4j-over-slf4j/1.7.12/d2444c9c7c1923304c25f86c5ee83a79a8166205/log4j-over-slf4j-1.7.12.jar
/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.apache.tomcat/tomcat-annotations-api/8.0.53/8be7e4f9b442515565083ac84df445007398881b/tomcat-annotations-api-8.0.53.jar
/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.eclipse.jdt/ecj/3.12.3/ade950992eb3caf6ab4f1a88706c755f0bf213d9/ecj-3.12.3.jar
/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-json/2.4.15/f6f6890181821246398cd44ba1fdf74f55717697/groovy-json-2.4.15.jar
/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/2.4.15/74b7e0b99526c569e3a59cb84dbcc6204d601ee6/groovy-2.4.15.jar
/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/commons-cli/commons-cli/1.2/2bf96b7aa8b611c177d329452af1dc933e14501c/commons-cli-1.2.jar
/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/commons-io/commons-io/2.4/b1b6ea3b7e4aa4f492509a4952029cd8e48019ad/commons-io-2.4.jar
/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.1.3/d90276fff414f06cb375f2057f6778cd63c6082f/logback-classic-1.1.3.jar
/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.12/8e20852d05222dc286bf1c71d78d0531e177c317/slf4j-api-1.7.12.jar
/Users/acabrerizo/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-core/1.1.3/e3c02049f2dbbc764681b40094ecf0dcbc99b157/logback-core-1.1.3.jar
```

**Comment by f4lco** [comment]
>  I'm trying to address is how to avoid different library versions loaded on the *servlet container classpath*

Gotcha. Sorry for the misunderstanding. I think the phrasing is a bit ambiguous, to me the "servlet container classpath" could refer to both the classpath of the class loader that loaded the servlet container, or the classpath the servlet container uses to spawn the webapp. Most of Gretty's users have trouble with the latter, and that's why I assumed to be your problem, too.

Very much _by design_, you'll encounter additional JARs on the JVM that runs the Tomcat that runs your app, from the 'root' or 'system' classloader. Gretty's code that configures Tomcat and communicates with the Gradle process spawning the runner has to live somewhere and that code has third-party dependencies, Groovy just being one of them.

I think you have just two options to go from here.

- The first one is patching and building Gretty 2.x by yourself. In 2.x, we have plugin-wide toggles in `gradle.properties`:
   https://github.com/gretty-gradle-plugin/gretty/blob/d17491b613fcf5b92b4a4ca7e4332ce7c17d09d2/gradle.properties#L27
   I can't guarantee those works as expected, but it would be worth a try. Unfortunately, I don't think we are doing releases for 2.x any more.
- Gretty 3 and 4 are under active development. It would be possible to add a toggle for the Groovy version, although it's a rare use-case. Currently, we default to the Groovy version that Gradle uses, and we only test Gretty against those versions. That's the relevant piece:
   https://github.com/gretty-gradle-plugin/gretty/blob/bfd7220948f47752e801869e27ffa04130358803/libs/gretty/src/main/groovy/org/akhikhl/gretty/DefaultLauncher.groovy#L34-L48
   Maybe that's already good enough for you to see if changing the Groovy version actually fixes your problem. A PR would be welcome, too. Sadly, changing the Groovy version on the runner classpath won't happen without a code change. So no, it's not possible to change the Groovy version via configuration of the plugin in your build at the moment, sorry.

**Comment by acabrerizosanchez** [comment]
Thank you for your help @f4lco, I really appreciate it.

 So If I have understood when managing a servlet container using gretty if the deployed webapp relies on groovy the option would be to align both (webapp and gretty) groovy dependencies (either recompiling gretty or adjusting the webapp). Well it sounds to me like the Heisenberg's uncertainty principle in the sense that you can not manage it (tomcat) without modifying its behaviour.

If that is the case, please, feel free to close the issue.

**Comment by f4lco** [comment]
Yes, currently I don' think we can change Gretty in a way to suit your need.
So in principle, I think it is possible to have different Groovy versions for Gretty and the app without interference, they are **not** tied together by design.
However, this only works if the app does not inquire about its environment, and uses only the webapp classloader. If you have a webapp that taps global state, and inspects for instance the system classloader, that app might have problems when deployed from Gretty. So a possible solution might include reworking the app such that it only sees the Groovy JARs present on the webapp classloader, which is under your control.
I agree with you that coupling the Groovy versions of the app and Gretty together is probably not a good idea. I mean, the Groovy version of Gretty is not reliable, it can change with every Gradle release. You might build the same project with different Gradle versions and get different results.
Best of luck!

**Comment by acabrerizosanchez** [comment]
Anyway, many thanks for your valuable help.
