### ISSUE TITLE
Configuring the way the server is stopped

### ISSUE THREAD

**Issue by p3k** [gretty-gradle-plugin/gretty#256]
If I start a server or farm with `appRun` or `farmRun` the server can be stopped by a simple press of a key. 

To me, it happens all the time that I accidentally enter something in the wrong terminal window (i.e. the one the server is running) and thus, undesirably stop the server.

I am used to stopping a process in the command line using `^C` and would be curious if there is a way to customize how the server can be stopped.

**Comment by f4lco** [comment]
Hello @p3k, this looks like a feature request to me. Currently, Gretty does not support that, although you are free to monkey-patch the task and launcher classes within your build.
I would think one could add this behavior to [`interactiveMode`](https://gretty-gradle-plugin.github.io/gretty-doc/Gretty-configuration.html#_interactivemode), this looks like an option for choosing a user interaction strategy to me.
If you want to go for it, new contributors are pretty much welcome, and @boris-petrov or me would surely give a review a shot 👍

**Comment by boris-petrov** [comment]
@p3k - have you also tried the `appStart`/`farmStart` tasks? I believe they do exactly what you want?

**Comment by p3k** [comment]
yes, indeed: `farmStart` seems to do the trick! thanks for the suggestion @boris-petrov 😺

**Comment by duersch-mms** [comment]
Haha easy win @p3k Thanks for checking back! 🎉

**Comment by f4lco** [comment]
Haha easy win @p3k 🎉  Thanks for checking back!
