### ISSUE TITLE
Support Jetty 10

### ISSUE THREAD

**Issue by ieugen** [gretty-gradle-plugin/gretty#267]
This issue is here to track support for Jetty 10. 

There are some library versions that would require using Jetty 10 instead of Jetty 9.

Support for Jetty 10 should be added to gretty-3.x branch. See https://github.com/gretty-gradle-plugin/gretty/issues/261 and https://github.com/gretty-gradle-plugin/gretty/issues/162

**Comment by boris-petrov** [comment]
Ah, I remember now why we didn't add Jetty 10. It supports Java 11+ while we want Java 8 support for Gretty 3 (because Tomcat 9 supports Java 8). Not sure we "want" but perhaps it's good to have. Not sure how many people depend on that... @f4lco do you have a specific opinion on that?

**Comment by ieugen** [comment]
Jetty 10 comes with older Java EE servlet namespace while Jetty 11 uses akartaEE Namespace namespace. 
See https://www.eclipse.org/jetty/download.php . 

> What Version Do I Use?
> The decision to use Jetty 10 or 11 depends entirely on which flavor of servlet package name needs to be used. June 1st, 2022 marks the end of community support for the Jetty 9.4.x release branch.

**Comment by f4lco** [comment]
> There are some library versions

@ieugen Which libraries are you referring to? Some very compelling/popular ones? I really would like to learn more about that. 

@boris-petrov yes, that's the reason. Precisely,
- We built Gretty 3 with JDK 8 and javax
- We built Gretty 4 with JDK 11 and jakarta

and Jetty 10 does not fit as JDK 11, but javax. Therefore, we cannot put Jetty 10 into existing releases cleanly.

I am not sure what to do, some of the options:

1. Raise the minimum JDK requirement for Gretty 3, if possible. Leave JDK 8 users in the dark.
2. Spawn Gretty 3.1 with a raised JDK requirement, and live with three supported versions of Gretty
3. Do a lot of build engineering, and release Gretty 3.x with two variants: one artifact qualifier for JDK 8, and a second one for JDK 11, compiled with the respective JDK

Possibly, there are more options...

"Good" news is that the branch https://github.com/gretty-gradle-plugin/gretty/compare/gretty-3.x...gretty-gradle-plugin:gretty:jetty10 contains a big chunk of work already. I did the work back in the day until realizing merging into 3.x was not feasible. The branch is up for grabs.

**Comment by schteff** [comment]
This would be very helpful for us since we have recently moved to Java 11 from Java 8 and would like to keep using gretty as development server without Jetty 11 which clashes with other libs we are using. 

Any of the three suggested options would work for us :)

We currently have jetty-annotations 9.2.14 (could most likely move to 10.x) and GWT 2.9.0 in our classpaths that clashes with Jetty 11.

**Comment by f4lco** [comment]
@schteff @ieugen we just pushed Gretty 3.1.0 through, which supports Jetty 10 🎉 
Any feedback is greatly appreciated, please check if you can put it to use.

**Comment by schteff** [comment]
I'm trying to get it up and running, but I've ran into some issues. 

The current problem(s) seems to be validation related. 

I'm getting the following errors

```
...
Caused by: A MultiException has 3 exceptions.  They are:
1. java.lang.NoSuchMethodError: 'javax.validation.ParameterNameProvider javax.validation.spi.ConfigurationState.getParameterNameProvider()'
2. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of org.glassfish.jersey.server.validation.internal.ValidationBinder$ConfiguredValidatorProvider errors were found
3. java.lang.IllegalStateException: Unable to perform operation: resolve on org.glassfish.jersey.server.validation.internal.ValidationBinder$ConfiguredValidatorProvider
...
```

I'm using jersey 2.37. Are there any known compatibility issues I should be aware of? 

The app runs fine on Tomcat 9.0.67 using Java 11 on our server, but I'm trying to get the local dev environment up and running again using Java 11. 

Should I maybe ask questions in the Gitter channel or is it ok to use this thread?

**Comment by ieugen** [comment]
Will check it out when I have some time (I hope this month).
Thank you for looking into this.

**Comment by f4lco** [comment]
> I'm trying to get it up and running, but I've ran into some issues.
> 
> The current problem(s) seems to be validation related.
> 
> I'm getting the following errors
> 
> ```
> ...
> Caused by: A MultiException has 3 exceptions.  They are:
> 1. java.lang.NoSuchMethodError: 'javax.validation.ParameterNameProvider javax.validation.spi.ConfigurationState.getParameterNameProvider()'
> 2. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of org.glassfish.jersey.server.validation.internal.ValidationBinder$ConfiguredValidatorProvider errors were found
> 3. java.lang.IllegalStateException: Unable to perform operation: resolve on org.glassfish.jersey.server.validation.internal.ValidationBinder$ConfiguredValidatorProvider
> ...
> ```
> 
> I'm using jersey 2.37. Are there any known compatibility issues I should be aware of?
> 
> The app runs fine on Tomcat 9.0.67 using Java 11 on our server, but I'm trying to get the local dev environment up and running again using Java 11.
> 
> Should I maybe ask questions in the Gitter channel or is it ok to use this thread?

@schteff yeah probably Gitter is the better place, you can also fil a new bug report if you are convinced it's connected to the Gretty upgrade. I would think Gretty has no connection to the classes inside packages like "javax.validation". To be sure, I recommend inspecting dependencies before and after upgrading Gretty, and then diffing them. This can help: https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html

**Comment by schteff** [comment]
Thanks for the suggestions, I don't have any further feedback other than it seems to start fine except for my compatibility issues. Good work!

I had to set `servletContainer = 'jetty10'` and remove the `logDir` and `logFileName` parameters in my gretty config. But that felt pretty standard.
