### ISSUE TITLE
Register/release org.gretty plugin with Gradle Central Plugin Repository https://plugins.gradle.org/

### ISSUE THREAD

**Issue by javabrett** [gretty-gradle-plugin/gretty#27]
Currently this works:

**build.gradle**
```
plugins {
  id "org.akhikhl.gretty" version "2.0.0"
}

apply plugin: 'war'

repositories {
  jcenter()
}

gretty {
  servletContainer = 'jetty9.4'
  httpPort = 8080
}
```

... due to the registration at https://plugins.gradle.org/plugin/org.akhikhl.gretty .  `org.gretty` (release 2.1.0) is not registered so the equivalent:

```
plugins {
  id "org.gretty" version "2.1.0"
}
```
... does not work.  This issue is about setting-up the best publishing-mechanism according to https://plugins.gradle.org/docs/publish-plugin and following that for either 2.1.0 or 2.2.0.

**Comment by wolfs** [comment]
Please publish to the plugin portal directly and don't push releases to jcenter.

Do you have some use-case for publishing releases to jcenter, too?

**Comment by javabrett** [comment]
@wolfs Thanks for pointing-out the preferred release vehicle for plugins.  I'm fairly new to the newer DSL-based plugin API and central repo.

To be honest, this being the first release post-fork and without a documented release-process, my posture was to mostly reverse-engineer what the last release looked-like, and only make necessary changes to things I couldn't understand or make work, then follow-up with improvements in subsequent releases.  The plugin-publish step hasn't been run yet for 2.1.0 and it remains to be seen whether that can be done for 2.1.0 and how well it will work, but I have no reason to believe that it won't.

Important to note that Gretty has quite a bit of packaging and dynamic assignment of dependencies - take a look at the list published to https://bintray.com/javabrett/maven/org.gretty/2.1.0#files/org%2Fgretty%2Fgretty - there's the plugin jar itself `gretty`, some core code `gretty-core`, a base container runner `jetty-runner`, then specific runners for the different servlet container runtimes and versions.  Currently, even if you use the plugin DSL for the previous release `2.0.0`, you need to add `jcenter()` as a repo to resolve the remainder (as well as non-Gradle dependencies such as `servlet-api` etc. ... it appears that for `2.0.0` at least only the plugin entry-point is served from the central repo.

So I suppose my first question is ... is https://plugins.gradle.org/m2 designed to be a generic Maven repo for such a multi-module build as Gretty, where there's a small actual plugin, then a lot of modules in-support?  I can't see why not but thought I'd ask.  Currently this is split across plugins.gradle and Bintray/JCenter.

Second question: Bintray has a nice GPG-sign-on-upload feature, yielding e.g. https://bintray.com/javabrett/maven/download_file?file_path=org%2Fgretty%2Fgretty%2F2.1.0%2Fgretty-2.1.0.jar.asc .  Does plugins.gradle have anything like that - if not, what do other plugin developers do in the main - don't sign or sign-locally?

Third question: what is the main advantage of uploading to plugins.gradle directly rather than Bintray/JCenter ... and is that advantage still relevant given how the 2.0.0 release worked with the small plugin and external dependencies?

Other reference URLs for this discussion:

- https://plugins.gradle.org/m2/org/akhikhl/gretty/org.akhikhl.gretty.gradle.plugin/2.0.0/org.akhikhl.gretty.gradle.plugin-2.0.0.pom
- https://plugins.gradle.org/m2/gradle/plugin/org/akhikhl/gretty/gretty/2.0.0/

**Comment by javabrett** [comment]
Well for 2.1.0 I checked-out the tag and just proceeded according to my understanding of how it was done for 2.0.0:

```
$ ./gradlew publishPlugins
[buildinfo] Not using buildInfo properties file for this build.

> Task :libs:gretty:publishPlugins 
Publishing plugin org.gretty version 2.1.0
Publishing artifact build/libs/gretty-2.1.0.jar
Publishing artifact build/libs/gretty-2.1.0-sources.jar
Publishing artifact build/libs/gretty-2.1.0-javadoc.jar
Publishing artifact build/libs/gretty-2.1.0-groovydoc.jar
Publishing artifact build/libs/gretty-2.1.0-sources.jar
Publishing artifact build/libs/gretty-2.1.0-javadoc.jar
Publishing artifact build/publish-generated-resources/pom.xml
Activating plugin org.gretty version 2.1.0


BUILD SUCCESSFUL in 20s
11 actionable tasks: 1 executed, 10 up-to-date
```

Now https://plugins.gradle.org/plugin/org.gretty exists and appears to work in plugin DSL, perhaps with a few bumps.  Is there a way to publish the dependency on `jcenter()` for the plugin?

Please open a new issue if there is a desire to move off Bintray/Jcenter and push everything to `plugins`.

**Comment by boris-petrov** [comment]
@javabrett - thanks a bunch for that! Perhaps you could document the steps for building/releasing/publishing somewhere in the README or some other document? For the future generations. :) Thanks again!
