### ISSUE TITLE
support slf4j-api:2.0.3

### ISSUE THREAD

**Issue by sonrocks1** [gretty-gradle-plugin/gretty#271]
could you please release a version that support slf4j 2.0.3, we are upgrading our dependencies and this is causing an issue as even the latest gretty plugin still uses slf4j 1.7.*

I need both org.gretty:gretty and org.gretty:gretty-runner-tomcat9 (both with same versions) is that possible

**Comment by boris-petrov** [comment]
@sonrocks1 do you mind sharing what's the error that you get when using slf4j 2.0.3?

**Comment by sonrocks1** [comment]
@boris-petrov here are the errors that we see:

SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions **1.7.x or earlier.**

this is because we have added the following to classpath:
      classpath "org.gretty:gretty:2.3.1"
      classpath "org.gretty:gretty-runner-tomcat9:2.3.1"

due to these it add the following dependencies:

grettyRunnerTomcat9
\--- org.gretty:gretty-runner-tomcat9:2.3.1
     +--- org.gretty:gretty-runner-tomcat85:2.3.1
     |    \--- org.gretty:gretty-runner-tomcat8plus:2.3.1
     |         \--- org.gretty:gretty-runner-tomcat:2.3.1
     |              +--- org.gretty:gretty-runner:2.3.1
     |              |    +--- org.codehaus.groovy:groovy:2.4.15
     |              |    +--- org.codehaus.groovy:groovy-json:2.4.15
     |              |    |    \--- org.codehaus.groovy:groovy:2.4.15
     |              |    +--- commons-cli:commons-cli:1.2
     |              |    +--- commons-io:commons-io:2.4
     |              |    \--- ch.qos.logback:logback-classic:1.1.3
     |              |         +--- ch.qos.logback:logback-core:1.1.3
     |              |         \--- **org.slf4j:slf4j-api:1.7.7 -> 1.7.12**
     |              \--- **org.slf4j:log4j-over-slf4j:1.7.12**
     |                   \--- **org.slf4j:slf4j-api:1.7.12**


it seems that slf4j 2.* is not compatible with slf4j 1.7.*

that is why i want a gretty release which supports slf4j 2.*

**Comment by sonrocks1** [comment]
@boris-petrov any update

**Comment by boris-petrov** [comment]
@sonrocks1 here we support only Gretty 3.x and 4.x. Would you mind testing with the latest 3.x release to see if you get the same issue?

**Comment by f4lco** [comment]
@sonrocks1 @ArLau we just pushed 3.1.0 through, can you please check if the issue with slf4j persists?
Please be aware we needed to remove support for Logback, too, because of the slf4j 1.x / 2.x ecosystem split.
Please re-open this ticket or file a new one as needed.
