### ISSUE TITLE
Some logger properties missing when upgrading from 3.0.6 to 3.1.1

### ISSUE THREAD

**Issue by Katharsas** [gretty-gradle-plugin/gretty#284]
In `build.gradle`:
```
// Embedded Tomcat/Jetty Configuration
gretty {
	httpPort = 8080
	contextPath = '/GMM'
	servletContainer = "tomcat9"
	serverConfigFile = "tomcat.xml" // Connectors for HTTP2 can be specified in this file
	recompileOnSourceChange = false // call javaCompile to reload or auto reload
	enableNaming = true // enable JNDI in context.xml for embedded tomcat
	
	// gretty container log (has nothing to to with GMM's log)
	logDir = "$projectDir/build"
	logFileName = "gretty"
}
```

However, when I upgrade to 3.1.1, i get the following gradle error:
```
> Could not set unknown property 'logDir' for extension 'gretty' of type org.akhikhl.gretty.GrettyExtension.
```
The same happens for `logFileName `. Have these properties been removed or renamed?

**Comment by f4lco** [comment]
Hello @Katharsas! Yes, indeed, we removed those logging properties. Please use & configure the logging facilities of your servlet container.

It basically became impossible (too much of a burden) to support those logging toggles with the addition of Jetty 10 to Gretty 3, because now the ecosystem is split between slf4j 1.x / 2.x, and the respective Logback versions.
That Logback added servlet-related code into their main distribution also did not help, because of the javax.servlet / jakarta.servlet split.
Sometimes navigating the dependency net becomes an exercise in constraint solving 😄

**Comment by Katharsas** [comment]
So gretty logs are by default going into the container logs? I think thats how it should be anyway, thanks!

**Comment by f4lco** [comment]
Haha exactly our thoughts as well ❤️ 
 It's unclear why Gretty has been a little invasive on the application before - like putting Logback on the application classpath by default, and or leaking the Gretty logger into the application logging config, etc and so forth.

**Comment by Katharsas** [comment]
This part of the docs can probably be simplified / removed:
https://gretty-gradle-plugin.github.io/gretty-doc/Logging.html

**Comment by f4lco** [comment]
Thanks, let me create a ticket for that. Over time, and multiple upgrades in third-party dependencies, this did not hold true:

> Gretty isolates its own logging from the web application logging on the level of ClassLoader. That means: the logback library (and logback configuration) used by Gretty is not visible within web application. You are free to use any logging system - logback, log4j, commons-logging etc. - within your web applications.

I can assure you, it's also nightmarish to debug...

**Comment by Katharsas** [comment]
> That Logback added servlet-related code into their main distribution also did not help, because of the javax.servlet / jakarta.servlet split.

That seems... not great (im currently moving to jakarta with a small webapp myself) ^^
And yeah, dealing with issues around multiple classloaders is scary xD
