### ISSUE TITLE
JDK10 testing/support

### ISSUE THREAD

**Issue by javabrett** [gretty-gradle-plugin/gretty#32]
JDK10 has been released.  This is a skeleton issue to track testing and support for Gretty and various containers which will support JDK10 (Jetty 9.4.9 is released and claims support).

Note that [Travis support is pending](https://github.com/travis-ci/travis-ci/issues/9368).

**Comment by henrik242** [comment]
I guess we at least need to wait for Groovy and Gradle to release something that includes asm 6.1:

Ref:
- https://github.com/apache/groovy/commit/b3e042191a7acc1c7bdfdfdc0c39fe93e2de3d94
- https://github.com/apache/groovy/commit/82c0cf629ed9a3494ea32a47b0d80fb96bc2b579
- https://github.com/gradle/gradle/pull/4696

**Comment by boris-petrov** [comment]
Gradle 4.7 is out with ASM 6.1.1 and Java 10 support. Groovy has [updated](https://github.com/apache/groovy/commit/12069be392048d953cc7033a9bf7ce0e99339455) ASM to 6.1.1 however I don't think they'll release anything that includes it any time soon. Is that a showstopper for us?

**Comment by henrik242** [comment]
Groovy 2.5.0-rc-1 has asm 6.1.1: https://github.com/apache/groovy/blob/GROOVY_2_5_0_RC_1/build.gradle#L143

**Comment by javabrett** [comment]
Closing this - `oraclejdk9` has been replaced in Travis by `oraclejdk10`.
