### ISSUE TITLE
Release 2.2.0

### ISSUE THREAD

**Issue by javabrett** [gretty-gradle-plugin/gretty#36]
Placeholder issue for Release 2.2.0 discussion and finalisation/release.

**Done**

- #37 (implementation-scope dependencies)
- #30 (Tomcat 8.5)

**Defer to 3.x, possible backport**

- #40 Upgrade to Groovy 2.5 GA when final

**Comment by henrik242** [comment]
I've upgraded a few versions, it looks fine. I feel like bumping groovy to the 2.5 RC. Are there any strong feelings against it? (It works great for me locally.)

**Comment by henrik242** [comment]
Groovy 2.5 PR here: https://github.com/gretty-gradle-plugin/gretty/pull/40

**Comment by javabrett** [comment]
@henrik242 Re Groovy 2.5 I left a note on the PR re watching to see how close to a final that release might be.  I'm also waiting on RC2 for a fix to https://issues.apache.org/jira/browse/GROOVY-8541 .

Would certainly like to see that upgrade in 2.2.0, but see #37 might start to get a few duplicates logged and justify say a 2.1.1.

**Comment by javabrett** [comment]
Proposal in #43 to make 2.2.0 (and a 2.x, 2.2.x branch) terminal for support of a bunch of things, including JDK7, very old/EOL containers (Jetty 7/8 and perhaps others).  So either we release this from master (simplest) or branch before landing any of the bigger upgrade items (Spring Boot 2, Groovy, JDK10).

**Comment by henrik242** [comment]
Sounds good

**Comment by boris-petrov** [comment]
Dropping JDK7 support (although I doubt many people still use it as upgrading to JDK8 is a no-brainer) means a breaking change so I suggest putting a 3.0.0 version number. This doesn't mean that we can't update Groovy and whatever else is needed for JDK10 support (apart from Spring) on the 2.x branch also.

**Comment by javabrett** [comment]
> This doesn't mean that we can't update Groovy and whatever else is needed for JDK10 support (apart from Spring) on the 2.x branch also.

True, but would it be necessary and beneficial?  The idea here is to make 3.0 the release to target the newer platforms (removing support for old), and leave 2.x uncomplicated by those.  I'm expecting that not many will be looking for a release which needs to simultaneously support the old and new platforms.

Assuming 3.0 can be released as soon as the platform-support is ready, is there any strong need to backport these to 2.x?  I say backport because I think 2.2 should be released with the Tomcat 8.5 support and the couple of bugfixes, and that it can go before the 3.0 features will be finalised.
