### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by javabrett** [gretty-gradle-plugin/gretty#50]
Issue to collect release 3.0.0 tasks and commentary.

# TODO
- See https://github.com/gretty-gradle-plugin/gretty/projects/1
- Deprecate JDK7 #49 
- Deprecate Gradle 1.x support #47 
- Deprecate Jettty 7+8 #51 
- Spring Boot 2 #43 
- Groovy 2.x #40

**Comment by JiangHongTiao** [comment]
guys, how do you see it? I would love to use it with Spring Boot 2, Gradle 5.4 and Tomcat 9. Is there any vision to continue with release?

**Comment by javabrett** [comment]
Gretty 3.x has been released.
