### ISSUE TITLE
ArtifactResolveException: Could not resolve all files for configuration 'grettyRunnerTomcat7'

### ISSUE THREAD

**Issue by johnjaylward** [gretty-gradle-plugin/gretty#77]
After upgrading to 2.2.0 I get this error. The documentation says that Tomcat 7 is still supported, so I'm not sure why it's not being found.

In order to get it to work, I had to add `jcenter()` to my project repository section (as opposed to the build script repository)

I'd prefer to keep jcenter in the buildscript section only if possible.

**Comment by javabrett** [comment]
Can you provide:
- How you added Gretty to your project before the upgrade
- How you have it added post-upgrade

**Comment by johnjaylward** [comment]
It's a multi-project setup with only 1 sub project using Gretty. Gretty is configured directly on the sub project like so:

Pre upgrade:
```guava
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        // tomcat integration
        classpath 'org.akhikhl.gretty:gretty:+'
    }
}

apply plugin: 'war'
apply plugin: 'org.akhikhl.gretty'


gretty {
    servletContainer = 'tomcat7'
    jvmArgs = ['-Dorg.jboss.logging.provider=slf4j']
    contextPath = '/'
    //    contextConfigFile="$projectDir/src/test/resources/jetty-env.xml"
    contextConfigFile = "$projectDir/src/test/resources/tomcat-context.xml"

    fastReload = false
    recompileOnSourceChange = false
    reloadOnClassChange = false
    reloadOnConfigChange = false
    reloadOnLibChange = false

    enableNaming = true

    debugSuspend = false

    //extraResourceBase "${project.buildDir}/scripts"
    extraResourceBase "${projectDir}/src/test/resources/"

    afterEvaluate {
        // ... some code specific to class path setup for SAP integration
    }
}
```

After:
```guava
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        // tomcat integration
        classpath 'org.gretty:gretty:+'
    }
}

apply plugin: 'war'
apply plugin: 'org.gretty'

repositories {
    // needed for gretty as-of gretty-2.2.0
    jcenter()
}

gretty {
    servletContainer = 'tomcat7'
    jvmArgs = ['-Dorg.jboss.logging.provider=slf4j']
    contextPath = '/'
    //    contextConfigFile="$projectDir/src/test/resources/jetty-env.xml"
    contextConfigFile = "$projectDir/src/test/resources/tomcat-context.xml"

    fastReload = false
    recompileOnSourceChange = false
    reloadOnClassChange = false
    reloadOnConfigChange = false
    reloadOnLibChange = false

    enableNaming = true

    debugSuspend = false

    //extraResourceBase "${project.buildDir}/scripts"
    extraResourceBase "${projectDir}/src/test/resources/"

    afterEvaluate {
        // ... some code specific to class path setup for SAP integration
    }
}
```

**Comment by johnjaylward** [comment]
If it matters, I only every run gretty using the `./gradlew clean appRunWarDebug` . I never use the raw `appRun` or `appDebug` tasks because they often have trouble pulling in all the dependencies of the sibling projects under the common root. I haven't tried in years though as I just got used to using the `appRunWarDebug` task

**Comment by johnjaylward** [comment]
I don't particularly want more repositories in my main build being checked and slowing things down on my build server when checking project dependencies. By adding jcenter into my main project repository list, now every dependency has to be verified against my existing repos + jcenter.  I don't use jcenter for any other dependencies and would prefer not to. It just adds one more place where some hack could lead to bad code getting into one of my builds.

It's not a super-must-fix-now concern, but it would be nice to reduce repository dependencies as much as possible.

**Comment by javabrett** [comment]
I'm investigating getting these into Maven Central also.

**Comment by javabrett** [comment]
I'm closing this wontfix. PRs considered especially from maintainers happy to help maintain dual releases to jcenter and Maven Central.
