### ISSUE TITLE
Gretty plugin resolves Gradle configurations in a user-managed thread

### ISSUE THREAD

**Issue by ghale** [gretty-gradle-plugin/gretty#80]
I wanted to provide a heads up around a coming Gradle deprecation that will affect the Gretty plugin.  With Gradle 5.0, we will output a deprecation warning whenever a configuration is resolved outside of a Gradle-managed thread.  The reason for this is because configuration resolution is an event that modifies the Gradle project model and if multiple threads are changing the model at the same time, this can produce inconsistent results.  In 5.0, we are introducing some safety for this in Gradle-managed threads, but we can't guarantee safety in user-managed threads.  The gretty plugin is resolving a configuration [here](https://github.com/gretty-gradle-plugin/gretty/blob/master/libs/gretty/src/main/groovy/org/akhikhl/gretty/DefaultLauncher.groovy#L33) that is being executed in a user-managed thread started [here](https://github.com/gretty-gradle-plugin/gretty/blob/master/libs/gretty-core/src/main/groovy/org/akhikhl/gretty/LauncherBase.groovy#L236) and produces a deprecation warning when run with Gradle 5.0.

To avoid this warning, I believe there's a fairly simple fix.  Instead of resolving the configuration inside of the spawned thread, the plugin should resolve the configuration in the task thread (which is Gradle-managed) immediately before spawning the child thread.  This will allow the configuration to be resolved safely under Gradle's control and then only the resolution results will be used in the user-managed thread.

From a reproduction/testing perspective, the first Gradle 5.0 RC is due out next week, but in the meantime, nightly builds are available [here](https://gradle.org/nightly/).

I hope that makes sense - if it doesn't, I'm happy to answer any questions or help with finding an alternate solution if the one proposed is not workable for some reason.

**Comment by boris-petrov** [comment]
@javabrett - this issue is a showstopper for using Gretty with Gradle 6. Have you tried to investigate or anything? Do you think the solution mentioned by @ghale is feasible?
