### ISSUE TITLE
getFreeRandomPort() should work for httpsPort

### ISSUE THREAD

**Issue by jzheaux** [gretty-gradle-plugin/gretty#85]
Doing

```groovy
gretty {
    httpPort = getRandomFreePort()
}
```
is super-convenient for integration tests.

Is there any reason that it is not supported for HTTPS?

For example, in [`TomcatServerConfigurer`](https://github.com/gretty-gradle-plugin/gretty/blob/master/libs/gretty-runner-tomcat/src/main/groovy/org/akhikhl/gretty/TomcatServerConfigurer.groovy#L107), it checks the `httpPort` property, but [not the httpsPort property](https://github.com/gretty-gradle-plugin/gretty/blob/master/libs/gretty-runner-tomcat/src/main/groovy/org/akhikhl/gretty/TomcatServerConfigurer.groovy#L133,L134).

**Comment by javabrett** [comment]
I'm not immediately aware of why this wouldn't be possible.  So a PR would be gratefully accepted if you get that working.

**Comment by jzheaux** [comment]
Sure, @javabrett.

Any possibility of backporting to the 2.x release train?

**Comment by javabrett** [comment]
Yes this was committed to the 2.x branch then merged to master.
