### ISSUE TITLE
Not Working With Java 9 and Overiding Jetty 9.4

### ISSUE THREAD

**Issue by ankurpathak** [gretty-gradle-plugin/gretty#89]
Its not working with Java 9 if we oveide version of Jetty 9.4 to latest in gradle.properties
with property:
jetty94Version = 9.4.13.v20181111

**Comment by javabrett** [comment]
JDK9 is not a long-term-support release and is already End of Life (EOL) for some time.  Are you after JDK9 support for a specific reason, or can you just use JDK11 LTS or JDK8?
