### ISSUE TITLE
buildProduct task fails when used with Gradle 5.0-rc-3

### ISSUE THREAD

**Issue by chali** [gretty-gradle-plugin/gretty#91]
When I'm using Gretty 2.2.0 with latest Gradle 5.0-rc-3 my build fails when executing following command `./gradlew buildProduct --stacktrace` with this error:

```
Caused by: org.gradle.api.InvalidUserDataException: No value has been specified for property 'logbackConfig'.
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.report(ValidatingTaskExecuter.java:67)
        ... 28 more
```

My project configuration is:
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "org.gretty:gretty:2.2.0"
    }
}

repositories {
    mavenCentral()
}

apply plugin: 'java'
apply plugin: 'war'
apply plugin: "org.gretty"

gretty {
    jacocoEnabled = false
    httpPort = 8080
    contextPath = '/'
    servletContainer = 'tomcat8'
    scanDirs = ['**/src/main/resources/**']
    scanDependencies = true
}
```

Here is a complete example project: https://github.com/chali/grettyMissingLogbackConfig

I was looking at the code here https://github.com/gretty-gradle-plugin/gretty/blob/master/libs/gretty/src/main/groovy/org/akhikhl/gretty/ProductConfigurer.groovy#L77-L80 and it looks like that the property `protected String logbackConfig` is never set so input for `buildProduct` task is set to `null`. Gradle 5.0 is more strict about input validation so it started to fail.

**Comment by chali** [comment]
I created #92 to do that. Please, let me know your thoughts.

**Comment by javabrett** [comment]
Possibly related to this change d62a87ba0929ee3b3e445bfc85b38e6c0a51680f .

**Comment by chali** [comment]
@javabrett do you think you can make 2.2.1 release including this? Or is there anything open which would cause a problem?

**Comment by javabrett** [comment]
The branch is currently targeted for 2.3, and snapshots are being deployed to e.g. https://oss.jfrog.org/artifactory/oss-snapshot-local/org/gretty/gretty-core/2.3.0-SNAPSHOT/ .  I'd be inclined to release that rather than a 2.2.1 with this change backported.  Any concerns with that?

Any chance you could configure that snapshot repo in one of your projects and run your testing and see if it is good for you, maybe adding feedback to #93 ?

**Comment by chali** [comment]
2.3 sounds good. I will test the snapshot.

**Comment by chali** [comment]
I tested the snapshot and I don't see the failure anymore.
