### ISSUE TITLE
Gradle 5.0 support

### ISSUE THREAD

**Issue by javabrett** [gretty-gradle-plugin/gretty#93]
Issue tracking overall Gradle 5.0 testing and support.  Note that this issue is about being able to **run** Gretty in a Gradle 5.0 build - there may be additional tasks to change Gretty to **build** itself using Gradle 5.0.

Travis build matrix now has a cross-test for Gradle 5.0-rc-4.  Not sure whether it is best/sound approach - it is possible that we will see some odd recompilation/executions etc., and the approach might need tweaking.  Also asked for CI advice at https://discuss.gradle.org/t/plugin-project-ci-e-g-travis-integration-tests-cross-gradle-versions/29569 .

This shows some different first-failures on branches:

**gretty-2.x**
https://travis-ci.org/gretty-gradle-plugin/gretty/jobs/457836792#L1687
```
> Task :libs:gretty:compileGroovy FAILED
startup failed:
/home/travis/build/gretty-gradle-plugin/gretty/libs/gretty/src/main/groovy/org/akhikhl/gretty/scanner/BaseScannerManager.groovy: 146: The class java.util.Map<WebAppConfig> (supplied with 1 type parameter) refers to the class java.util.Map<K,V> which takes 2 parameters
 @ line 146, column 9.
           Map<WebAppConfig> webAppProjectReloads = [:]
           ^
1 error
```
Suspect a Groovy version change triggers that - interesting that it compiles under 4.x.  Not sure why it is recompiling - might need to tweak the test launch.

**master**
https://travis-ci.org/gretty-gradle-plugin/gretty/jobs/457863512#L1655
```
FAILURE: Build failed with an exception.
* Where:
Build file '/home/travis/build/gretty-gradle-plugin/gretty/libs/gretty-runner-tomcat/build.gradle' line: 10
* What went wrong:
A problem occurred evaluating project ':libs:gretty-runner-tomcat'.
> Could not get unknown property 'VersionNumber' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
```
Again, this seems to be rebuilding with 5.0 rather than testing with it.

/cc #91 #80

**Comment by chali** [comment]
> Not sure why it is recompiling - might need to tweak the test launch.
Matrix build executes the whole build process with different parameters. So in this case it will use Gradle 5.x wrapper compile and test everything again. It is scary that groovy compiled this before :-)

**Comment by chali** [comment]
Here is how you can write a test which takes the same compiled code and use it with different versions of Gradle https://docs.gradle.org/current/userguide/test_kit.html#sub:gradle-runner-gradle-version

**Comment by javabrett** [comment]
Thanks, raised #94 to look into TestKit.

In the interim, I [put in a workaround](https://github.com/gretty-gradle-plugin/gretty/compare/5cd3826124b4e86ae821b7b5f137ffaedad5d998...gretty-gradle-plugin:gretty-2.x#diff-354f30a63fb0907d4ad57269548329e3R52) to run the (root project) `integrationTests` task `testAll` directly, rather than as a `GradleBuild` from the main project, since the Gradle 4.x->5.0 change seemed to cause recompilation and issues.  That seems to be more stable.
