### ISSUE TITLE
org.gretty:gretty-starter:2.3.0 artifact is missing from Bintray

### ISSUE THREAD

**Issue by javabrett** [gretty-gradle-plugin/gretty#98]
Per discussion in #96.  Will need to see if this can be built/uploaded as a single module, or whether 2.3.1 will be required to address this.

- http://dl.bintray.com/javabrett/maven/org/gretty/gretty-starter/
- https://bintray.com/javabrett/maven/org.gretty/2.3.0#files/org%2Fgretty%2Fgretty-starter

Reported by @chali

**Comment by matsandreassen** [comment]
Can I ask why this was closed? It still seems to be happening.

**Comment by javabrett** [comment]
Was a GH autoclose from a commit I pushed which upgraded jfrog plugins.

Reopened. Releasing 2.3.1 is probably the safest fix for this.

**Comment by chali** [comment]
@javabrett I approved #101 let me know if I can help anyhow to get 2.3.1 out.

**Comment by javabrett** [comment]
Released 2.3.1.
